Organize helm files
Move everything relative to helm to the "helm" folder. The helm upgrade
command was failing because it was considering other files from our
repository.

    Error: create: failed to create: Request entity
    too large: limit is 3145728

We also updated the "README.md" to add the missing parameter related to
the gitlab merge request label.

Co-authored-by: Alexandre Eher <alexandre.eher@werkspot.nl>
Signed-off-by: Jefersson Nathan <malukenho.dev@gmail.com>